language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
matrix:
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4
services:
  - memcached
install: python setup.py install
before_script: pip install nose
script: nosetests
